name: Deploy (staging)
'on': workflow_dispatch
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_STAGING }}
      APP_ENV: staging
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn
      - run: yarn run build
      - run: npx firebase deploy --project $APP_ENV
