name: Deploy (production)
'on':
  push:
    branches: [main]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      APP_ENV: production
      NODE_ENV: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn
      - run: npx firebase deploy --project $APP_ENV
